services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: employeeDB
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - '5434:5432'
    restart: always