services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=employeeDB'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433'
    restart: always